### PR TITLE
Issue #11, Shift all the three dots menu to navigation drawer

### PR DESCRIPTION
**Pull request by wseemann**

### CODE REVIEW

**Review by Kvaibhav01 — COMMENTED** [review]
Awesome work. Can you add relevant icons alongside the drawer options?  
Also, for the area where a user's avatar is shown in the drawer, add the app logo along with its name at the bottom of the logo.

**Comment by wseemann** [comment]
Can you provide me with the relevant icons?

**Comment by Kvaibhav01** [comment]
You can use these:

- Did you feel it? (https://www.flaticon.com/free-icon/information_906794#term=question&page=1&position=4)
- More apps (https://www.flaticon.com/free-icon/playstore_1077105#term=playstore&page=1&position=4)
- Fork on GitHub (https://www.flaticon.com/free-icon/code-fork-symbol_25406#term=fork&page=1&position=17)
- Get Notification alert (https://www.flaticon.com/free-icon/turn-notifications-on-button_60977#term=notification&page=1&position=10)
- About (https://www.flaticon.com/free-icon/information_157933#term=information&page=1&position=12)

**Comment by Kvaibhav01** [comment]
Closing this PR as no active activity/contributions are seen.

**Pull request closed without merging**
